import * as v from "valibot";

export const settingsSchema = v.object({
  bankName: v.pipe(v.string(), v.minLength(1)),
  bankCode: v.pipe(v.string(), v.minLength(1)),
  restaurantName: v.pipe(v.string(), v.minLength(1)),
  accountPhone: v.pipe(v.string(), v.minLength(1)),
  accountRif: v.pipe(v.string(), v.minLength(1)),
  transferBankName: v.string(),
  transferAccountName: v.string(),
  transferAccountNumber: v.string(),
  transferAccountRif: v.string(),
  orderExpirationMinutes: v.pipe(v.number(), v.integer(), v.minValue(5)),
  maxPendingOrders: v.pipe(v.number(), v.integer(), v.minValue(1)),
  maxQuantityPerItem: v.pipe(v.number(), v.integer(), v.minValue(1)),
  rateCurrency: v.picklist(["usd", "eur"]),
  showRateInMenu: v.boolean(),
  rateOverrideBsPerUsd: v.optional(v.string()),
  activePaymentProvider: v.picklist([
    "banesco_reference",
    "mercantil_c2p",
    "bnc_p2c",
    "whatsapp_manual",
  ]),
  banescoApiKey: v.optional(v.string()),
  mercantilClientId: v.optional(v.string()),
  mercantilClientSecret: v.optional(v.string()),
  mercantilSecretKey: v.optional(v.string()),
  mercantilMerchantId: v.optional(v.string()),
  mercantilIntegratorId: v.optional(v.string()),
  mercantilTerminalId: v.optional(v.string()),
  bncApiKey: v.optional(v.string()),
  whatsappNumber: v.optional(v.string()),
  whatsappMicroserviceUrl: v.optional(v.string()),
  adicionalesEnabled: v.optional(v.boolean()),
  bebidasEnabled: v.optional(v.boolean()),
  instagramUrl: v.optional(v.string()),
  orderModeOnSiteEnabled: v.optional(v.boolean()),
  orderModeTakeAwayEnabled: v.optional(v.boolean()),
  orderModeDeliveryEnabled: v.optional(v.boolean()),
  packagingFeePerPlateUsdCents: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0))),
  packagingFeePerAdicionalUsdCents: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0))),
  packagingFeePerBebidaUsdCents: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0))),
  deliveryFeeUsdCents: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0))),
  deliveryCoverage: v.optional(v.string()),
  paymentPagoMovilEnabled: v.optional(v.boolean()),
  paymentTransferEnabled: v.optional(v.boolean()),
});

export type SettingsInput = v.InferOutput<typeof settingsSchema>;
